import fse from 'fs-extra'
import {writeWithBackup} from './fs-helpers.js'

import {APP_STATE_DIR, CUSTOM_TOML, SETTINGS_JSON, ZCASH_CONF, ZEBRA_DIR, ZEBRAD_TOML} from '../../lib/paths.js'
import {restart} from '../bitcoind/bitcoind.js'
import {
	DefaultValuesForVersion,
	LATEST,
	resolveVersion,
	schemaForVersion,
	settingsMetadataForVersion,
	type SettingsSchema,
	type SelectedVersion,
} from '#settings'

const NON_TOML_KEYS = new Set<string>(['version'])

let cachedSettings: SettingsSchema | undefined

function mergeWithDefaults(partial: Partial<SettingsSchema>): SettingsSchema {
	const selectedVersion = ((partial as {version?: SelectedVersion})?.version ?? LATEST) as SelectedVersion
	const resolvedVersion = resolveVersion(selectedVersion)
	const defaults = DefaultValuesForVersion(resolvedVersion) as Record<string, unknown>
	return {...defaults, ...partial} as SettingsSchema
}

function filterSettingsForVersion(input: Record<string, unknown>, selectedVersion: SelectedVersion): Record<string, unknown> {
	const resolvedVersion = resolveVersion(selectedVersion)
	const allowedKeys = new Set(Object.keys(settingsMetadataForVersion(resolvedVersion)))
	const filteredSettings: Record<string, unknown> = {}
	for (const [key, value] of Object.entries(input)) {
		if (allowedKeys.has(key)) filteredSettings[key] = value
	}
	return filteredSettings
}

async function loadAndValidateSettings(): Promise<SettingsSchema> {
	const partial = (await fse.readJson(SETTINGS_JSON).catch(() => ({}))) as Partial<SettingsSchema> & {version?: string}

	if (!('chain' in partial) && process.env['DEFAULT_CHAIN']) {
		;(partial as Record<string, unknown>)['chain'] = process.env['DEFAULT_CHAIN']
	}

	const selectedVersion = (partial?.version as SelectedVersion) ?? LATEST
	const merged = mergeWithDefaults(partial)
	const filtered = filterSettingsForVersion(merged as Record<string, unknown>, selectedVersion)
	return schemaForVersion(selectedVersion).parse(filtered) as SettingsSchema
}

function tomlString(value: string): string {
	return JSON.stringify(value)
}

function generateManagedToml(settings: SettingsSchema): string {
	const p2pPort = process.env['P2P_PORT'] || '8233'
	const rpcPort = process.env['RPC_PORT'] || '8232'
	const network = settings['chain'] === 'Testnet' ? 'Testnet' : 'Mainnet'
	const listen = settings['listen'] !== false
	const listenAddr = listen ? `0.0.0.0:${p2pPort}` : `127.0.0.1:${p2pPort}`
	const peerTarget = Number(settings['peerset_initial_target'] ?? 25)
	const maxPerIp = Number(settings['max_connections_per_ip'] ?? 1)

	const lines = [
		'# Generated by Zcash Node. Managed keys live in this file.',
		'# Add extra tables or keys under Advanced → custom overrides; they are merged on save.',
		'',
		'[network]',
		`network = ${tomlString(network)}`,
		`listen_addr = ${tomlString(listenAddr)}`,
		`peerset_initial_target_size = ${peerTarget}`,
		`max_connections_per_ip = ${maxPerIp}`,
		'',
		'[rpc]',
		`listen_addr = ${tomlString(`0.0.0.0:${rpcPort}`)}`,
		'enable_cookie_auth = false',
		'parallel_cpu_threads = 0',
		'',
		'[state]',
		`cache_dir = ${tomlString(ZEBRA_DIR)}`,
		'',
	]

	for (const key of Object.keys(settings)) {
		if (NON_TOML_KEYS.has(key)) continue
	}

	return lines.join('\n')
}

type TomlTables = Record<string, Record<string, string>>

function parseSimpleToml(text: string): TomlTables {
	const tables: TomlTables = {}
	let current = 'root'
	tables[current] = {}

	for (const raw of text.split('\n')) {
		const line = raw.trim()
		if (!line || line.startsWith('#')) continue
		const section = line.match(/^\[([^\]]+)\]$/)
		if (section) {
			current = section[1]
			tables[current] ??= {}
			continue
		}
		const eq = line.indexOf('=')
		if (eq === -1) continue
		const key = line.slice(0, eq).trim()
		const value = line.slice(eq + 1).trim()
		tables[current][key] = value
	}

	return tables
}

function serializeToml(tables: TomlTables, banner: string): string {
	const chunks: string[] = [banner.trimEnd(), '']
	const order = Object.keys(tables).filter((name) => name !== 'root')
	const root = tables['root'] ?? {}
	for (const [key, value] of Object.entries(root)) {
		chunks.push(`${key} = ${value}`)
	}
	if (Object.keys(root).length) chunks.push('')

	for (const name of order) {
		chunks.push(`[${name}]`)
		for (const [key, value] of Object.entries(tables[name] ?? {})) {
			chunks.push(`${key} = ${value}`)
		}
		chunks.push('')
	}

	return chunks.join('\n')
}

function mergeToml(generated: string, custom: string): string {
	if (!custom.trim()) return generated.endsWith('\n') ? generated : `${generated}\n`

	const base = parseSimpleToml(generated)
	const overlay = parseSimpleToml(custom)
	for (const [section, keys] of Object.entries(overlay)) {
		base[section] ??= {}
		for (const [key, value] of Object.entries(keys)) {
			base[section][key] = value
		}
	}

	return serializeToml(base, '# Generated by Zcash Node (custom overrides merged).')
}

function generateZcashConf(): string {
	const rpcPort = process.env['RPC_PORT'] || '8232'
	return [
		'# Used by lightwalletd to find this node. Zebra ignores rpcuser/rpcpassword when cookie auth is off.',
		'rpcbind=127.0.0.1',
		`rpcport=${rpcPort}`,
		'rpcuser=lightwalletd',
		'rpcpassword=lightwalletd',
		'',
	].join('\n')
}

async function writeGeneratedFiles(settings: SettingsSchema): Promise<void> {
	const custom = await fse.readFile(CUSTOM_TOML, 'utf8').catch(() => '')
	const merged = mergeToml(generateManagedToml(settings), custom)
	await writeWithBackup(ZEBRAD_TOML, merged.endsWith('\n') ? merged : `${merged}\n`)
	await writeWithBackup(ZCASH_CONF, generateZcashConf())
}

export async function ensureConfig(): Promise<SettingsSchema> {
	await fse.ensureDir(APP_STATE_DIR)
	await fse.ensureDir(ZEBRA_DIR)

	const settings = await loadAndValidateSettings()
	const contents = JSON.stringify(settings, null, 2) + '\n'
	await writeWithBackup(SETTINGS_JSON, contents)
	await writeGeneratedFiles(settings)
	return settings
}

export async function getSettings(): Promise<SettingsSchema> {
	if (!cachedSettings) cachedSettings = await loadAndValidateSettings()
	return cachedSettings
}

export async function updateSettings(patch: Partial<SettingsSchema>): Promise<SettingsSchema> {
	const current = await getSettings()
	const selectedVersion = ((patch as {version?: SelectedVersion})?.version ??
		(current as {version?: SelectedVersion})?.version ??
		LATEST) as SelectedVersion
	const resolvedVersion = resolveVersion(selectedVersion)

	const mergedWithDefaults = {
		...(DefaultValuesForVersion(resolvedVersion) as Record<string, unknown>),
		...(current as Record<string, unknown>),
		...(patch as Record<string, unknown>),
	}
	const filtered = filterSettingsForVersion(mergedWithDefaults as Record<string, unknown>, selectedVersion)
	const merged = schemaForVersion(selectedVersion).parse(filtered) as SettingsSchema

	await writeWithBackup(SETTINGS_JSON, JSON.stringify(merged, null, 2) + '\n')
	await writeGeneratedFiles(merged)
	await restart()

	cachedSettings = merged
	return merged
}

export async function restoreDefaults(): Promise<SettingsSchema> {
	const defaults = DefaultValuesForVersion(resolveVersion(LATEST)) as SettingsSchema
	if (process.env['DEFAULT_CHAIN']) (defaults as Record<string, unknown>)['chain'] = process.env['DEFAULT_CHAIN']

	await writeWithBackup(SETTINGS_JSON, JSON.stringify(defaults, null, 2) + '\n')
	await writeGeneratedFiles(defaults)
	await restart()

	cachedSettings = defaults
	return defaults
}

export async function getCustomOptions(): Promise<string> {
	await fse.ensureFile(CUSTOM_TOML)
	return (await fse.readFile(CUSTOM_TOML, 'utf8')).trimEnd()
}

export async function updateCustomOptions(rawText: string): Promise<string> {
	const userLines = rawText.replace(/\r\n/g, '\n').trimEnd()
	await writeWithBackup(CUSTOM_TOML, userLines ? `${userLines}\n` : '')
	const settings = await getSettings()
	await writeGeneratedFiles(settings)
	await restart()
	return userLines
}
