import {describe, it} from 'node:test'
import assert from 'node:assert/strict'
import {parse} from 'smol-toml'

import {InvalidTomlError, mergeToml, parseToml} from './toml.ts'

const GENERATED = `# Generated by Zcash Node. Managed keys live in this file.

[network]
network = "Mainnet"
listen_addr = "0.0.0.0:8233"
peerset_initial_target_size = 25
max_connections_per_ip = 1

[rpc]
listen_addr = "0.0.0.0:8232"
enable_cookie_auth = false

[state]
cache_dir = "/data/zebra"
`

const BANNER = '# merged'

describe('mergeToml', () => {
	it('keeps multi-line array overrides intact (issue #5 reproduction)', () => {
		const custom = [
			'[network]',
			'initial_mainnet_peers = [',
			'  "dnsseed.z.cash:8233",',
			'  "mainnet.seeder.zfnd.org:8233",',
			']',
			'',
			'[mempool]',
			'eviction_memory_time = "1 h"',
		].join('\n')

		const merged = mergeToml(GENERATED, custom, BANNER)
		const doc = parse(merged) as Record<string, Record<string, unknown>>

		assert.deepEqual(doc['network']['initial_mainnet_peers'], ['dnsseed.z.cash:8233', 'mainnet.seeder.zfnd.org:8233'])
		assert.equal(doc['network']['network'], 'Mainnet')
		assert.equal(doc['network']['peerset_initial_target_size'], 25)
		assert.equal(doc['mempool']['eviction_memory_time'], '1 h')
		assert.equal(doc['rpc']['enable_cookie_auth'], false)
		assert.ok(merged.startsWith(`${BANNER}\n`))
	})

	it('lets overrides replace managed scalars without touching sibling keys', () => {
		const merged = mergeToml(GENERATED, '[network]\npeerset_initial_target_size = 60', BANNER)
		const doc = parse(merged) as Record<string, Record<string, unknown>>

		assert.equal(doc['network']['peerset_initial_target_size'], 60)
		assert.equal(doc['network']['listen_addr'], '0.0.0.0:8233')
		assert.equal(doc['state']['cache_dir'], '/data/zebra')
	})

	it('merges nested tables and preserves inline comments and multi-line strings', () => {
		const custom = [
			'[tracing]',
			'filter = "info" # keep it quiet',
			'',
			'[tracing.extra]',
			'note = """',
			'two',
			'lines"""',
		].join('\n')

		const doc = parse(mergeToml(GENERATED, custom, BANNER)) as Record<string, Record<string, unknown>>

		assert.equal(doc['tracing']['filter'], 'info')
		assert.deepEqual(doc['tracing']['extra'], {note: 'two\nlines'})
	})

	it('rejects invalid overrides instead of emitting a broken document', () => {
		assert.throws(
			() => mergeToml(GENERATED, '[network]\ninitial_mainnet_peers = [\n', BANNER),
			(err: unknown) => err instanceof InvalidTomlError && err.statusCode === 400,
		)
	})
})

describe('parseToml', () => {
	it('accepts an empty document', () => {
		assert.deepEqual(parseToml(''), {})
	})

	it('reports the offending line in a 400 error', () => {
		assert.throws(
			() => parseToml('[network]\nlisten_addr = '),
			(err: unknown) => {
				assert.ok(err instanceof InvalidTomlError)
				assert.equal(err.statusCode, 400)
				assert.match(err.message, /^Invalid TOML on line 2: /)
				return true
			},
		)
	})
})
