version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: zec-zcash-node_app_1
      APP_PORT: 3000

  app:
    image: ghcr.io/nickpio/umbrel-zcash:v0.1.3
    user: '1000:1000'
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - '${APP_ZCASH_P2P_PORT}:${APP_ZCASH_P2P_PORT}'
      - '${APP_ZCASH_RPC_PORT}:${APP_ZCASH_RPC_PORT}'
      - '${APP_ZCASH_WALLET_PORT}:${APP_ZCASH_WALLET_PORT}'
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      CHAIN_STATE_DIR: /data/zebra
      APP_STATE_DIR: /data/app
      LIGHTWALLETD_DIR: /data/lightwalletd
      APPS_SUBNET: ${NETWORK_IP}/16
      P2P_PORT: ${APP_ZCASH_P2P_PORT}
      RPC_PORT: ${APP_ZCASH_RPC_PORT}
      WALLET_PORT: ${APP_ZCASH_WALLET_PORT}
      TOR_HOST: ${APP_ZCASH_TOR_PROXY_IP}
      TOR_SOCKS_PORT: 9050
      TOR_CONTROL_PORT: 9051
      TOR_CONTROL_PASSWORD: moneyprintergobrrr
      BITCOIND_IP: 127.0.0.1
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      P2P_HIDDEN_SERVICE: ${APP_ZCASH_P2P_HIDDEN_SERVICE}
      RPC_HIDDEN_SERVICE: ${APP_ZCASH_RPC_HIDDEN_SERVICE}
      WALLET_HIDDEN_SERVICE: ${APP_ZCASH_WALLET_HIDDEN_SERVICE}
    networks:
      default:
        ipv4_address: $APP_ZCASH_NODE_IP

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: torer
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/tor:/data
    environment:
      HOME: '/tmp'
    networks:
      default:
        ipv4_address: $APP_ZCASH_TOR_PROXY_IP
